CREATE TABLE users (
    user_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nom VARCHAR(40) NOT NULL,
    prenom VARCHAR(40) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(40) NOT NULL
);

CREATE TABLE task (
    task_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nom VARCHAR(40) NOT NULL,
    description Text NOT NULL,
    status VARCHAR(40) NOT NULL,
    user_id INT NOT NULL,
    CONSTRAINT fk_task_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE RESTRICT ON UPDATE CASCADE
);
