spring.application.name=portfolio
spring.datasource.url=jdbc:postgresql://localhost:5432/todolist
spring.datasource.username=todolist
spring.datasource.password=todolist
spring.jpa.hibernate.ddl-auto=validate

jwt.secret=0crYWy0YcfHVHChtz1p93D+oOQFrWDICLAnyaMwdavS70j3oZHv1kZPC3gTa2Ij7+8bzSjWjEzubU4Q/wgsJlQ==
jwt.expiration-ms=3600000
